notifications:
  email: false

install:
  - pip3 install .
script:
  - pip3 install nose2 nose2-cov
  - nose2 --with-coverage

jobs:
  include:
    - name: "Python 3.8 on Xenial Linux"
      language: python
      python: 3.8
      before_install:
        - pip3 install codecov
        - sudo chmod +x linux_so.sh
        - ./linux_so.sh
      after_success: codecov
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - chmod 755 macos_dylib.sh
        - ./macos_dylib.sh
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install -U pip
        - pip install --user wheel
        - ./create_dll.bat
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - stage: lint
      language: python
      python: 3.8
      install: pip install flake8
      script:
        # stop the build if there are Python syntax errors or undefined names
        - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        - flake8 . --exit-zero
