notifications:
  email: false

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install --user -r requirements.txt; fi
  - pip install .
script:
  - pip install pytest~=3.6.1 pytest-cov~=2.4
  - pytest --cov=geodesic

jobs:
  include:
    - name: "C++ Test"
      language: cpp
      compiler: gcc
      install: [] # disable global install
      script:
      - sudo chmod +x cpptest.sh
      - ./cpptest.sh
    - name: "Python 3.8 on Xenial Linux"
      language: python
      python: 3.8
    - name: "Python 2.7 on Xenial Linux"
      language: python
      python: 2.7
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - pip install --user wheel
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 2.7 on Windows"
      os: windows
      language: shell
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
      before_install:
        - choco install python2 vcredist2008 ; choco install --ignore-dependencies vcpython27
        - python -m pip install --upgrade pip
        - pip install --user wheel
    - stage: lint
      language: python
      python: 3.8
      install: pip install flake8
      script:
        # stop the build if there are Python syntax errors or undefined names
        - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        - flake8 . --exit-zero
